### ISSUE TITLE
Wrong LEDs light up

### ISSUE THREAD

**Issue by EstherJohanna** [bk1285/rpi_wordclock#105]
Hallo Bernd, vielen Dank für die ausführliche Anleitung! Die Wordclock ist unser erstes Raspi-Projekt und wir haben die LEDs tatsächlich zum Leuchten gebracht. Leider zeigen sie nicht die richtigen Wörter an. Nun fragen wir uns, an welcher Stelle wir etwas falsch gemacht haben. Wir haben dein Wiring benutzt, aber keine Buttons angebracht. Deshalb haben wir bei der Anzahl der LEDs das +4 auskommentiert und das Wordclock Interface auf type = gpio_high gestellt. Das Foto zeigt unseren Aufbau. Viele Grüße, Laura und Esther 

![img-0678](https://user-images.githubusercontent.com/28892057/49828555-0eee4d00-fd41-11e8-867d-c1d5ea67baf6.JPG)

**Comment by bk1285** [comment]
Hallo Laura, hallo Esther,

auf dem Bild sind die 110 LEDs für die Buchstaben zu sehen, die 4 Minuten LEDs fehlen da noch: 2 direkt am Raspberry, 2 am Ende des LED-Strips.

Wenn's danach noch Probleme gibt, einfach nochmal melden.

Viel Erfolg!
Bernd

**Comment by bk1285** [comment]
... siehe auch: https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_layouts/german_11x10/wiring_front_bernds_wiring.png

**Comment by bk1285** [comment]
Bei weiteren Fragen issue bitte wieder öffnen.
