### ISSUE TITLE
Summer/Winter Time

### ISSUE THREAD

**Issue by MaxZimmermann99** [bk1285/rpi_wordclock#109]
Hey Leute mir zeigt die Uhr die falsche Uhrzeit an :) In der config steht "Berlin". Muss ich irgendwo Sommer und Winterzeit aktivieren?

**Comment by HeerNMeester** [comment]
Hi Max,

I had the same issue.
Check if the time zone in your Raspberry Pi is set correctly, which was not in my case:
`sudo raspi-config`

**Comment by MaxZimmermann99** [comment]
Oh you are right. Its sometimes so easy.... Thanks a lot!

tags: wrong time, summer time, winter time, local time,
