### ISSUE TITLE
Color Wheel on web interface not working with white

### ISSUE THREAD

**Issue by bhunziker** [bk1285/rpi_wordclock#117]
Hi all

First of all, let me thank you all for this great project!

I realized that when setting the default color to WHITE in the time_default plugin (line 47-49) the color wheel does not work any more. My workaround is to change the color before handing it to the web, but this is not nice. Any other ideas how to fix it?

**Comment by bk1285** [comment]
Hi @bhunziker 

I just had the chance to check this, but cannot reproduce the issue, using latest develop, master.

Is it possibly browser specific? Can you test with another browser/device/...

Best,
Bernd

**Comment by bhunziker** [comment]
Hi Bernd

Thanks a lot for your fast and useful reply. I checked it it with the latest master and realized it works. So I have to do some homework to find out what's different.
The browser (chrome, IE, safary) has no influence.
