### ISSUE TITLE
No more soldering

### ISSUE THREAD

**Issue by viezefreddie91** [bk1285/rpi_wordclock#118]
After destroying my LED strip twice because of my genius soldering, i found these “double connectors”. Just wanna share..

https://m.nl.aliexpress.com/item/32870470660.html?pid=808_0009_0101&spm=a2g0n.search-amp.list.32870470660&aff_trace_key=e7f289f08a6541f2b8f323627bc35e62-1548465616450-07303-cWkwJnjS&aff_platform=msite&m_page_id=470amp-UeAh5rejSePDYH1n4dqQnw1553108817837

**Comment by bk1285** [comment]
Hey @viezefreddie91,

thanks for sharing! I'll add them to the list of components... :)

Best,
Bernd

**Comment by bk1285** [comment]
Here we go... https://github.com/bk1285/rpi_wordclock/commit/ebfa30599b06184313b6d5857e15de421299b8d7

**Comment by gielk** [comment]
@viezefreddie91 The link no longer works, which one did you buy? Do you maybe have the name you found it with on AliExpress?

**Comment by sezijlema** [comment]
I have not used or tried them but I think he means e.g. these: https://www.aliexpress.com/item/1005001521762588.html
Depending on your LED strip, you will need a certain version.

For the Dutchies among us, here's a local option as well: https://www.tinytronics.nl/shop/nl/verlichting/led-strips/accessoires/led-strip-connector-15cm-3p-10mm-ws2811-ws2812b

If these links die as well, I found them by searching for "LED strip Connector (cable)".

**Comment by gielk** [comment]
> I have not used or tried them but I think he means e.g. these: https://www.aliexpress.com/item/1005001521762588.html Depending on your LED strip, you will need a certain version.
> 
> For the Dutchies among us, here's a local option as well: https://www.tinytronics.nl/shop/nl/verlichting/led-strips/accessoires/led-strip-connector-15cm-3p-10mm-ws2811-ws2812b
> 
> If these links die as well, I found them by searching for "LED strip Connector (cable)".

thanks 

dankjewel! Heb jij er al een gebouwd of ben je het van plan?
