### ISSUE TITLE
cannot fetch index base url http //pypi.python.org/simple/

### ISSUE THREAD

**Issue by MfBosch** [bk1285/rpi_wordclock#127]
Hallo Zusammen,
kann mir jemand weiterhelfen ? ich bekomm bei der instalation mehrere Packete (netifaces
flask-restplus) diese Fehlermeldung:
cannot fetch index base url http //pypi.python.org/simple/
Vielen Dank

**Comment by bk1285** [comment]
Hi @MfBosch,

maybe take a look here: https://stackoverflow.com/questions/21294997/pip-connection-failure-cannot-fetch-index-base-url-http-pypi-python-org-simpl

* Are you possibly using a vpn connection?
* http vs. https might be an issue, so maybe try to specify the https explicitly as proposed within the link above...

Best,
Bernd

**Comment by bk1285** [comment]
Please reopen, if still unresolved.
