### ISSUE TITLE
Question about hole diameter in skeleton

### ISSUE THREAD

**Issue by Calimerorulez** [bk1285/rpi_wordclock#131]
Hi!

Thank you for this awesome project!

Excuse me for asking, but what is the hole diameter of the holes I have to drill in the skeleton? I'm having a hard time to find it :(

**Comment by HeerNMeester** [comment]
Depends on the size of your clock and letters. The standard is a letter matrix of 30x30 cm, in that case the holes should be around 24 mm. Depending on the type of wood you use for the frame, and your ability to drill holes, you can increase that to 25 mm of even 26 mm. but in the latter case the walls between the holes might get really thin. So to be "better safe than sorry", use 24 mm.

**Comment by Calimerorulez** [comment]
Thanks!
