### ISSUE TITLE
Wired wrong direction, how to fix

### ISSUE THREAD

**Issue by O365Tycho** [bk1285/rpi_wordclock#135]
I didn't pay attention and wired my clock in a different direction. As you can see in the attached image i started with the minute leds in the top left corner, followed by bottom left corner and then went up,down,up,down etc with the led strings. This results in the leds being vertically mirrored (don't know how else to describe it).  

What is the best way to fix this? I found wordclock_plugins/time_default/time_dutch.py and think i can probably make the time work by modifying the ranges in this file, but that probably doesn't resolve the issue with other plugins.

![wordclock](https://user-images.githubusercontent.com/10546703/68247103-6745d180-001a-11ea-92c1-00ffbc0cb9e7.jpg)

ps. Did a git pull today and am now getting errors on the web interface. Should i create an issue for it or is it something i'm doing wrong?
<img width="406" alt="wordclock_web" src="https://user-images.githubusercontent.com/10546703/68247451-2a2e0f00-001b-11ea-8337-97d0f41fee19.png">

**Comment by HeerNMeester** [comment]
Hi Tycho,

I see that rewiring is not really an easy option anymore.
The wiring of the LEDS is configured in this file:
https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_tools/wiring.py
You can create your own wiringscheme here and use that in the config file.

**Comment by O365Tycho** [comment]
Thanks for the link to the wiring scheme. I've added my own wiring class with the following formulas in the getStripIndexFrom2D(self,x,y)

`if x % 2 == 0:
   pos = (self.WCA_WIDTH -x) * self.WCA_HEIGHT -y + 1
else:
   pos = (self.WCA_WIDTH -x - 1) * self.WCA_HEIGHT + y + 2`
