### ISSUE TITLE
CNC dwg/svg/pdf format

### ISSUE THREAD

**Issue by kimthostrup** [bk1285/rpi_wordclock#137]
Hi all, this is a question rather than a question. 

Does anyone have a cnc ready vector file for the frame/base of the word clock ? 

Thanks in advance. 
/Kim

**Comment by phenze** [comment]
It is for a 45x45 wordclock.

https://drive.google.com/file/d/1Hlotmw6nANcubd6710GxPgvlm0991RH7/view?usp=sharing

**Comment by kimthostrup** [comment]
Thanks @phenze 😃
Do you happen to have a picture of the frame ?

**Comment by kimthostrup** [comment]
Thanks phenze, this is awesome 😃

**Comment by 3damberger** [comment]
dankeschön ;-)
