### ISSUE TITLE
WS2812B mit WS2811 Controller (Nachtrag #11)

### ISSUE THREAD

**Issue by tooliload** [bk1285/rpi_wordclock#14]
Hallo,

ich habe nun noch etwas neues probiert und bin zufällig auf etwas gestoßen.

Der WS2812B mit WS2811 Controller aktualisiert sich bei mir nur, wenn ich ihn kurz vom Strom trenne und erneut anschließe. Hast du eine Idee warum?

Die LED´s werden über den Python Script perfekt angesteuert, wenn ich dann das Netzteil vom WS2812B trenne und nach wenigen Sekunden wieder anschließe, leuchten die LED´s wieder aktuell. Wenn ich das Netzteil aber dauerhaft dran lasse, dann leuchten die LED´s zwar, aktualisieren sich aber nicht. -> Die Uhr bleibt stehen. (Gleiches auch bei dem Rainbow-Test, die LED´s aktualisieren sich nur, wenn der Strom kurz getrennt wird)

Ich habe nun erst einmal meinen alten Pi B+ am laufen. Die neue WS281x Lib für den Pi2 scheint zu funktionieren (zumindestens gab es keine Fehlermeldung), das die LED´s sich aber nicht aktualisieren, passiert auch hier.

p.s. hatte das andere Ticket #11 nicht aufbekommen.

**Comment by bk1285** [comment]
Hi @tooliload 

hm... um ehrlich zu sein, kann ich dieses Verhalten nicht erklaeren. Da jedoch auch der Rainbow-Test betroffen ist, vermute ich, dass es eine Fehlfunktion der library rpi_ws281x ist, die die LEDs ansteuert. Daher wuerde ich dir empfehlen dort mal direkt bei den Entwicklern nachzufragen.

Hoffe das hilft.

Beste Gruesse,
Bernd
