### ISSUE TITLE
Frontplate with 18x16 letters and the matrix plugin

### ISSUE THREAD

**Issue by Joeri-MS** [bk1285/rpi_wordclock#143]
I've got an 18x16 Frontplate working. But some Plugins, like Matrix, dosen't uses all LEDs, only the original 11x10 area are used.

In the matrix plugin.py i changed the width, but i did not find the right place to change the hight.

        # initialize rain start: set to end coordinate
        rain = [20 for _ in range(0, wcd.get_wca_width() + 1)]
        while True:

**Comment by bk1285** [comment]
@mrksngl any chance, to look into this?!? ;)

Best,
Bernd

**Comment by Joeri-MS** [comment]
I found the 2 Lines:
Line 38:
`        rain = [20 for _ in range(0, wcd.get_wca_width() + 1)]`
And Line 51:
`                    y1 = min(wcd.get_wca_height() + 1, y);`
