### ISSUE TITLE
Change sequence of minutes LED

### ISSUE THREAD

**Issue by DJ-Dan** [bk1285/rpi_wordclock#144]
I have change from Christians Bastel-Laden to this Raspberry Pi Wordclock.
But by me is the left top LED not LED one its LED four.
How can I change the sequence of the minutes LEDs?

**Comment by bk1285** [comment]
Hi @DJ-Dan 

you may update (or better reimplement) the [mapMinutes](https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_tools/wiring.py#L117) and the offset in [getStripIndexFrom2D](https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_tools/wiring.py#L103).

Best,
Bernd
