### ISSUE TITLE
Rückplatte

### ISSUE THREAD

**Issue by 3damberger** [bk1285/rpi_wordclock#149]
Gi . 

Hast du irgendwo eine svg oder zeichnung der rückplatte ? ich finde leider nur die Front. Würde die dann direkt komplett fräsen lassen

Gruß
    Marcus

**Comment by phenze** [comment]
Schau mal hier. Da ist auch die Zwischenplatte dabei.

https://github.com/bk1285/rpi_wordclock/issues/137
