### ISSUE TITLE
Changing minutes Position

### ISSUE THREAD

**Issue by Alphascrypt** [bk1285/rpi_wordclock#158]
Hey guys again,

i use bernds_wiring and wanted the minutes after the last LED. After Z,99

How is this possible?

Greetings
Martin

**Comment by bk1285** [comment]
Hi @Alphascrypt 

create your own wiring class in https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_tools/wiring.py according to your wiring layout. There are already different versions available. ...so you can take a look on how they did it.

Best,
Bernd

**Comment by bk1285** [comment]
Resolved? If not, feel free to reopen.
