### ISSUE TITLE
Some Points for troubleshooting section

### ISSUE THREAD

**Issue by euchkatzl** [bk1285/rpi_wordclock#16]
Hi,
i have some things that you could ad to the troubleshooting section.

1.) When the LED's do not light up as expected check if there is a ground connection from the pi to the LED Strip. That is absolutely necessary.

2.) Another problem could be that the LED Strips are connected in the wrong direction. Take care of the little arrow on the strips to connect them properly.

3.) a Wiring Layout from these pull up buttons were nice. Like you i'm also not an expert in electronics. I think a spent about 4 hours until i understood how to connect them. Perhaps anybody could create some pictures for dummies. (especially for the wordclock)

**Comment by bk1285** [comment]
Hi @euchkatzl , thanks for the feedback. Indeed, was working on a wiring layout. Now it's added to the documentation. I also added your comments to the troubleshooting section: https://github.com/bk1285/rpi_wordclock/commit/33f790120a43ad50b282521505033b7bdf73d85d

I'll add your bavarian layout soon! Thanks for sharing! :)

Regards,
Bernd
