### ISSUE TITLE
colorful light up

### ISSUE THREAD

**Issue by nUmb3rfive** [bk1285/rpi_wordclock#161]
Hi guys,
first of all, you did an awesome job creating this software! Thank you very much!
Unfortunately some issues are occurring in recent times. There appears sometimes a color pattern for 1 minute until the time changes (attached a picture). The LEDs also flicker in rainbow mode despite the use of a level shifter. Do you guys have any idea how to fix this issue?
![IMG_1753](https://user-images.githubusercontent.com/67592782/86018814-2033a300-ba26-11ea-81ce-53e441b679fd.jpg)
Thanks for your help in advance. If you need more informations for troubleshooting do not hesitate to ask.
Cheers,
Nicola

**Comment by FrankX0** [comment]
Always difficult to debug this from a distance.
All points to noise on the data line to the LED's, causing them to flicker or turn on, which is "corrected" when the actual time is written again. Good that you use a level shifter!

Did you try a different power-supply?
Can you make pictures (or drawing) of how your power (especially ground) and signal connections are running?

**Comment by echo1483** [comment]
Hallo Nicola,
hat zwar nichts damit zu tun. Was hast du als Streuscheibe für die LED´s benutzt.
Danke, echo

**Comment by nUmb3rfive** [comment]
No, it‘s actually difficult to find such a powerful power supply. I ordered this one directly in China. 
Specs of my power supply:
- Input Voltage: 100~240V AC
- Output Voltage: 5V DC
- Output Current: 10A
- Suggested Usage: LED display, communication

Thank you for your help! I really appreciate it!

@echo1483 : In my opinion PLEXIGLAS® of evonik works best as a diffusor for the wordclock. I used PLEXIGLAS® Resist WHITE 99532 GT, thickness: 0.5mm. I hope this helps.

More pictures:
![image](https://user-images.githubusercontent.com/67592782/86507384-18824e80-bdd8-11ea-86c2-e8c2e17a9d02.jpeg)
![image](https://user-images.githubusercontent.com/67592782/86507394-3059d280-bdd8-11ea-8eab-67e7003523b5.jpeg)
![image](https://user-images.githubusercontent.com/67592782/86507404-3a7bd100-bdd8-11ea-8fde-02ac83295603.jpeg)![image](https://user-images.githubusercontent.com/67592782/86507409-45cefc80-bdd8-11ea-9ab0-815483d2d8fd.jpeg)

**Comment by echo1483** [comment]
Thank you for your prompt reply.
echo

**Comment by phenze** [comment]
Take a look here:

* https://github.com/bk1285/rpi_wordclock/issues/110
* https://github.com/bk1285/rpi_wordclock/issues/106

Looks like you have no common ground.

**Comment by bk1285** [comment]
Reopen, if not resolved.
