### ISSUE TITLE
Modulimport für Temperatursensor verhindert Programmstart

### ISSUE THREAD

**Issue by SEBatHome** [bk1285/rpi_wordclock#17]
Hallo,

zunächst eine großes Lob für das tolle Projekt. Ich verfolge die Wordclock im Eigenbau Initiativen seit geraumer Zeit und freue mich, dass es jetzt eine Version mit dem Rapi gibt, die die Anzeigevarianten Temp etc. deutlich gegenüber der nur Zeitanzeige erhöht. Mangels  eigner Programmierfähigkeiten bin ich für die Vorlage sehr dankbar. Uhr ist (die letzen beiden Tage) gebaut und funktioniert, juhu.Ein humble Pi hat die Vedrahtung bei mir noch etwas vereinfacht. Den Spannungsausgleich, der im youtube video angesprochen wurde, konnte ich so auch leicht verbauen.

Bei der Installation bin ich jedoch auf zwei Hürden gestoßen. Zum einen hat der Programmstart nicht funktioniert, da er versucht hat das modul für am2302 zu laden, was nicht funktioniert hat. Laut Beschreibung ist es optional und bei mir der Sensor (noch nicht) nicht vorhanden. Bei Programmstart war es zumindest bei mir jedoch eine echte Bedingung, ohne die das Programm nicht weiter lädt. Mit der Deaktivierung in der plugin.py in Zeile 1 über ssh (#import am2302_ths) war das Problem (zumindest provisorisch) gelöst.

Ein zweites Problem trat zuvor bei der Installation der Software auf. Zur Installation des Phyton packages mit sudo pip install pytz astral feedparser pillow svgwrite freetype-py muss zuvor noch das ausgeführt werden:

$ sudo apt-get build-dep python-imaging
$ sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev

Jedenfalls war es bei mir so. Installation erfolgte auf einem alten RPi B Rev.2 mit Raspian Wheezy Stand heute.

Beste Grüße und nochmal Daumen hoch für das tolle Projekt. Die Anleitung auf Youtube war auch sehr Instruktiv.

**Comment by bk1285** [comment]
Hi @SEBatHome 

besten Dank fürs feedback! Freut mich zu hören, dass das Projekt in 2 Tagen realisierbar ist! :D
Den Import für den Temperatur-sensor habe ich gefixt... :)

Die weiteren installs füge ich der Troubleshooting section hinzu. Ich selbst konnte habe die packages bisher nicht installieren müssen... :)

Beste Grüße,
Bernd
