### ISSUE TITLE
Web app without internet connection

### ISSUE THREAD

**Issue by FabianReister** [bk1285/rpi_wordclock#177]
Currently, the web app fetches many resources (js, css, fonts) from a CDN.

I think, serving these resources locally would be beneficial:
- independent of internet connection -> faster, more reliable
- increased security

Example:

https://github.com/bk1285/rpi_wordclock/blob/d523f817f03835c05782703795a66e5f0ebdaf8d/wordclock_interfaces/templates/app.html#L9

**Comment by bk1285** [comment]
Agreed, @FabianReister

**Comment by FrankX0** [comment]
@FabianReister: the development branch now has all resources locally.
