### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by FabianReister** [bk1285/rpi_wordclock#178]
It is quite hard to identify errors on the command line as everything is printed without coloring. 

There are great libraries available, such as the **logging** library that allows to specify several logging levels. In conjunction with **coloredlogs**, the command line output would be

![image](https://user-images.githubusercontent.com/6173945/102775832-eff20f00-438d-11eb-97c1-47cc406bf9cc.png)

The only changes need to be made are

```
__main__:
  
  import logging
  logging.basicConfig(level=logging.DEBUG)
  
  import coloredlogs
  coloredlogs.install()
  print = logging.info
```
to wordclock.py' main function. This sets print to be an info message (available levels: DEBUG, INFO, WARNING, ERROR). 

**coloredlogs** can be installed from pypi (pip install coloredlogs) and could be wrapped with a try-catch-block to prevent import errors.

**Comment by bk1285** [comment]
Nice, @FabianReister I'll consider that.

**Comment by bk1285** [comment]
Thanks for the suggestion, @FabianReister :)
