### ISSUE TITLE
Night Mode - hardcoding values

### ISSUE THREAD

**Issue by R0lleston** [bk1285/rpi_wordclock#189]
Since the night mode (where the clock dims) isnt working correctly, what area of the code do i need to go to hardcode the values ?

**Comment by bk1285** [comment]
Here we go, @R0lleston :  https://github.com/bk1285/rpi_wordclock/blob/master/wordclock_plugins/time_default/plugin.py#L190

...but expect a fix to be provided for this (included in the port to python3).

Best,
Bernd
