### ISSUE TITLE
Feature Suggestion : automatic swapping between plugins

### ISSUE THREAD

**Issue by R0lleston** [bk1285/rpi_wordclock#192]
@bk1285 this idea follows on from the scrolling message plugin suggestion.
If say the wordclock was used in an environment such as a business for example, that wished to have a scrolling message play (e.g. welcoming a customer), but also wished to display the time, it would be quite neat to have a section that allows for automatically swapping between plugin for a preset time.

e.g. MESSAGE PLUGIN (30s) ==> TIME DISPLAY (30s) ==>  MESSAGE PLUGIN (30s)  ......

**Comment by bk1285** [comment]
To be handled with transitions in the future (no need to automatically swap plugins).

...but this is still work in progress..
