### ISSUE TITLE
Seconds plugin jumps numbers (bernd development version)

### ISSUE THREAD

**Issue by R0lleston** [bk1285/rpi_wordclock#199]
This could be similar issue to one that Bernd solved recently. But the seconds count plugin jumps number eg 31, 33, 34, 35, 36,38 (it's always jumps two positions). I haven't checked for time accuracy but it's something that needs looking at

**Comment by bk1285** [comment]
Hi @R0lleston, I tried to reproduce this on latest develop, but there are no jumps on my clock. Do you make any specific changes apart from latest develop?

Best,
Bernd

**Comment by R0lleston** [comment]
@bk1285 no changes at all. Happy to record a video of it an email it through to you

**Comment by R0lleston** [comment]
Uploading 20210809_215514.mp4…

**Comment by R0lleston** [comment]
https://user-images.githubusercontent.com/87622394/128692946-bab039ce-602e-4807-bca4-a05251f672db.mp4

**Comment by bk1285** [comment]
I see your point. Is it possible, that you have accidentally two instances of the software running? Use `pgrep python` via command line to determine the number of active python processes (should be one).

**Comment by bk1285** [comment]
Hi @R0lleston please reopen, if your issue persists..

Best,
Bernd

**Comment by R0lleston** [comment]
![16285735444198710683322642954785](https://user-images.githubusercontent.com/87622394/128813395-34664235-fdb4-43b9-94c7-a7776363c89c.jpg)
That's from the clock being turned on from cold. @bk1285 how do we fix this ?

**Comment by R0lleston** [comment]
![16285762967897934481965997297723](https://user-images.githubusercontent.com/87622394/128817717-adb6ecc3-64b9-4b8a-8402-3a28c5b15636.jpg)
@bk1285 it seems to be coming from wordclock.py

**Comment by R0lleston** [comment]
@bk1285 strangely enough this issue seems to have sorted itself out using @phenze development version using alot of your code.
