### ISSUE TITLE
Disable the three bouttons

### ISSUE THREAD

**Issue by dgeordgy21** [bk1285/rpi_wordclock#20]
Hi,
For my projet, I dont need the three bouttons. Please could we have the possibility ton disable them to avoid the "Pin 17 pressed." error.

**Comment by stefancarlton** [comment]
Checkout my fork for ideas... I disabled them too.

I also made it English / my word clock specific, but it'll help you understand what you need to change.

**Comment by bk1285** [comment]
Hi @dgeordgy21 

I provided a fix. If you checkout the latest version, you can update the config-file as follows:

```
    [wordclock_interface]
    type = gpio_high
```

Hope that helps. Otherwise, reopen again... :)

Regards,
Bernd
