### ISSUE TITLE
Wordclock keeps refreshing 

### ISSUE THREAD

**Issue by R0lleston** [bk1285/rpi_wordclock#204]
Just had this bug occur, but I couldn't record it unfortunately.  Wordclock is set up with typewriter mode, clock ticked over 7:59 PM, and kept refreshing screen time for the whole minute until 8pm kicked in, then corrected itself. I've spotted it occur on and off with the develop python 3 versions at different times.

Nice little bug for you

**Comment by R0lleston** [comment]
@bk1285 maybe it happens every hour. My daughter spotted this tonight @ 6:59pm and asked me why it kept refreshing the screen. Once 7pm kicked in, it started behaving again

**Comment by bk1285** [comment]
Please reopen, if still occuring, @R0lleston ..
