### ISSUE TITLE
Changing Color 

### ISSUE THREAD

**Issue by exgenera** [bk1285/rpi_wordclock#222]
Hi,

I cannot change color and brightness by accessing the wordclock via IP anymore (not IP an APi). If I access the clock, there is a cyrcle with all colors and a bar for brightness. It seem like the „execute“ after changing something is missing.

**Comment by sarosr** [comment]
Hi, me too
![Immagine 2022-05-09 145442](https://user-images.githubusercontent.com/51180215/167414913-82c6409e-a5ab-444d-bf07-ab89144a9491.jpg)

**Comment by phenze** [comment]
Take a look here.

https://github.com/bk1285/rpi_wordclock/issues/218

**Comment by bk1285** [comment]
@exgenera please reopen, if #218 does not resolve this.
