### ISSUE TITLE
Software install procedure needs some updates

### ISSUE THREAD

**Issue by kas1kas** [bk1285/rpi_wordclock#229]
Today [13-Oct-2022} I created a memorystick with the official Raspberry Pi imager (32 bit, no desktop).

Problems encountered following the software setup in the documentation and the fixes:

1: Download software, Clone the wordclock software with git clone ......
error: git is not yet installed, this is the next step in the instructions
solution: first do the 3rd party dependencies (packages). There are two sections, one towards the end. Do that one now as well.
(maybe put these two sections first in the documentation)

Every day software  dependancies seem to change because packages are upgraded.

2: Running the wordclock 
ImportError: cannot import name 'parse_rule' from 'werkzeug 
solution: downgrade werkzeug and flask (until the problem is fixed, I have no idea what the cause is)
sudo pip3 install flask==2.0.2
sudo pip3 install werkzeug==2.0.2
(maybe the requirements.txt file can be changed to take care of this)

success Kas

**Comment by bk1285** [comment]
Hi @kas1kas,

when I built the last clock a few month ago, git was already installed by default. However, I still updated the documentation according to your comment: Won't hurt to be on the safe side here.

Concerning the import error: Are you sure, that you were on latest main, when setting up the clock. flask + werkzeug dependencies were resolved on main a while ago.

I'll keep an eye on this anyways. Thanks for reporting.

Best,
Bernd
