### ISSUE TITLE
IR control

### ISSUE THREAD

**Issue by dgeordgy21** [bk1285/rpi_wordclock#23]
Hi all!
Finialy I have attached the tree bouttons and they are working!
But it's not practical at all especially if the clock is mounted on a wall...
My idea is to control the clock with a IR remote control.
I'm not a programmer, so I found this code seems to do the job.
Do you think you can atapt it?
http://ozzmaker.com/how-to-control-the-gpio-on-a-raspberry-pi-with-an-ir-remote/

**Comment by bk1285** [comment]
Hi @dgeordgy21 

I like the concept quite much. However I'd currently give #18 priority. If this work out well, you can control the clock with your smartphone or any other pc/laptop/tablet within your local network.

Regards,
Bernd

**Comment by bk1285** [comment]
Hi @dgeordgy21 
@euchkatzl reports to have a working remote control as mentioned in #18 Maybe you want to give it a try. :)
