### ISSUE TITLE
No Module named colored logs 

### ISSUE THREAD

**Issue by basholtman** [bk1285/rpi_wordclock#239]
<img width="1005" alt="Schermafbeelding 2023-01-08 om 16 39 39" src="https://user-images.githubusercontent.com/55329611/211205599-02d36ef1-4734-4a8e-926f-026643e9d191.png">

What's happening here? Installed everything as described in the manual.

**Comment by FrankX0** [comment]
The package "coloredlogs" should have been installed with `sudo pip3 install -r requirements.txt`.
You can install seperately: `sudo pip3 install coloredlogs`
Are you running Python3? Can you run the clock with `sudo python3 wordclock.py`?

**Comment by basholtman** [comment]
Hi Frank, 

thanks for the prompt reply. I’ll try sudo pip3 install -r requirements.txt later today. As it wasn’t in the software installation documentation of Bernd. Did I miss more? 

Running python 3.9.2, lite version installed via the raspbian imager. 

Build this project already about 4 years ago, can’t remember above step.

**Comment by FrankX0** [comment]
Hi Bas. A lot has changed in 4 years ;-)
This step is described in the [Software setup](https://rpi-wordclock.readthedocs.io/en/main/doc_software_setup.html#software-setup).
Please let me know if you still run into issues.

**Comment by basholtman** [comment]
I noticed, getting a bit further now. Still not able to run it due to werkzeug error, how do I read underneath error and correct it?

<img width="997" alt="Schermafbeelding 2023-01-08 om 19 53 10" src="https://user-images.githubusercontent.com/55329611/211213699-1787d4b7-350b-4dd1-9ac0-4bd453cffabe.png">

**Comment by FrankX0** [comment]
Seems related to issue #229 
Can you try:
```
sudo pip3 install flask==2.0.2
sudo pip3 install werkzeug==2.0.2
```

**Comment by basholtman** [comment]
<img width="1192" alt="Schermafbeelding 2023-01-09 om 19 17 37" src="https://user-images.githubusercontent.com/55329611/211379078-adf707c1-87dd-4922-b8c9-b9c284e449a3.png">

Seems to do the trick, Thank you a lot!

**Comment by FrankX0** [comment]
The time is taken from the Raspberry Pi. So my guess is that that time is incorrect.
Can you check that, and if needed, check the timezone in raspi-config?

**Comment by basholtman** [comment]
Everything works correctly now!
