### ISSUE TITLE
Can't start the wordclock in developer_mode

### ISSUE THREAD

**Issue by andupp** [bk1285/rpi_wordclock#252]
Hi,

I've been trying to get the wordclock to start up in developer_mode (setting the flag in the config to True). But I keep getting the following error:

```
> sudo python3 wordclock.py 
> 2023-09-05 00:25:23 rpiclock root[3950] INFO Software version: v1.0.0-dev-146-gf5c5bf4
> 2023-09-05 00:25:23 rpiclock root[3950] INFO Parsing /home/aup/rpi_wordclock/wordclock_config/wordclock_config.cfg
> Unable to access the X Display, is $DISPLAY set properly?
```

I have been googling my head off for that "Unable to access the X Display"-message, and nothing I do seems to help.

I'm using Mac OS X to ssh to the PI 3B+ that has the wordclock installed.
The PI 3B+ is running `Raspberry PI OS (64-bit)` with a port of Debian bullseye with the Raspberry PI Desktop.

Any ideas on how I can get the wordclock running in developer mode?

**Comment by FrankX0** [comment]
Just a thought: can you try this by connecting a monitor and keyboard? Not sure if this works through an ssh connection.
