### ISSUE TITLE
Uhrzeit wird angezeigt, zusätzlich jedoch weitere Buchstaben

### ISSUE THREAD

**Issue by Nthl25** [bk1285/rpi_wordclock#34]
Hallo,

ich habe gestern meine WordClock fertig gestellt und hatte kurzfristig die korrekte Uhrzeit in weißer Schrift auf meiner Uhr.

Wenige Sekunden später wechselte die Farbe zu blau und seither leuchten zusätzlich noch einige Buchstaben in weiß.

Hat jemand von euch eine Ahnung, woran das liegen könnte?
Die Blaue Farbe ist übrigens auch nicht durchgängig gleich hell/dunkel.

Grüße

**Comment by euchkatzl** [comment]
Hast du schon die Punkte von diesem Ticket überprüft ? 
https://github.com/bk1285/rpi_wordclock/issues/28

Der audio kernel war bei mir das problem.

Zusätzlich bitte mal den strandtest.py im rpi_wx /examples/python ordner ausführen und testen ob der richtig läuft.

**Comment by Nthl25** [comment]
Den Eintrag hatte ich ursprünglich schon gemacht.
Nachdem ich die Datei nochmal angelegt habe funktioniert es (Rechtschreibfehler waren keine drin...).

Danke dir für deine Hilfe!
