### ISSUE TITLE
wiring concept Grafik

### ISSUE THREAD

**Issue by ghwc2015** [bk1285/rpi_wordclock#4]
Hi Bernd,

beim Zusammenbau bin ich mit der Grafik "wiring concept" nicht so ganz klargekommen.
Nummerierung der x- und y-Achse scheint mir nicht zu passen.

Ich habe für mein wiring Schema deine Grafik angepasst - vielleicht magst du das mit in die Doku aufnehmen.
Ich habe unten noch das Schema für setColorBy1DCoordinates eingefügt - diese Nummerierung ist hilfreich für die unterschiedlichen Fronten.

Gruß
Timo

![wiring_concept_timo](https://cloud.githubusercontent.com/assets/10575598/6114483/bff7fe50-b09e-11e4-9bcc-05e7063ecacb.png)

**Comment by bk1285** [comment]
Hi Timo,
thanks for reporting. That's actually a bug in the manual... ;/
Regards,
Bernd

**Comment by bk1285** [comment]
Hi Timo,
danke fürs feedback. Habe ein skript hinzugefügt, welches es ermöglicht die wiring-layouts automatisch (und hoffentlich jetzt bug-frei) zu generieren... ;)
Bernd
