### ISSUE TITLE
Fragen zur Nutzung der Buttons

### ISSUE THREAD

**Issue by Nthl25** [bk1285/rpi_wordclock#43]
Hallo,

meine Wortuhr funktioniert inzwischen dank der Anleitung wunderbar, vielen Dank schonmal dafür. Jedoch habe ich das Problem, dass ich die Buttons nicht ans Laufen bekomme.

Dauerhaft erhalte ich die Meldung: "Pin 17 pressed".

Die Buttons sind anhand der [Anleitung](https://rpi-wordclock.readthedocs.io/en/latest/_images/wiring.png) verkabelt und angeschlossen. Muss ich sonst noch etwas beachten?

In dem  [Video](https://youtu.be/V9TwvranJnY?t=1026) ist noch ein kleiner Controller zwischengeschaltet (jedenfalls sieht dies so aus).
Handelt es sich dabei um den Temperatursensor oder was genau ist das?

Vielen Dank für eure Hilfe.

Nhtl.

**Comment by bk1285** [comment]
Hi @Nthl25 

schau mal hier nach dem 3. Punkt: https://rpi-wordclock.readthedocs.io/en/latest/doc_troubleshooting.html

Falls es nicht klappt, einfach nochmal melden. Der Controller ist ein touch-sensor (anstatt der Buttons)

Beste Grüße,
Bernd
