### ISSUE TITLE
type = gpio_high but it still says "Pin 17 pressed"

### ISSUE THREAD

**Issue by Nthl25** [bk1285/rpi_wordclock#46]
Hi,

I set the "type" in my configfile to gpio_high but when starting the wordclock-script, “Pin 17 pressed” is logged all the time. Do you have any ideas what this could be?

nthl

**Comment by bk1285** [comment]
you tested with gpio_low as well, right?

**Comment by Nthl25** [comment]
I tried both. But I always get the message "Pin 17 pressed".

**Comment by bk1285** [comment]
:/ ok. I'll try to reproduce with the latest version of the software as soon as I can...

**Comment by Nthl25** [comment]
I get the same problem if  i  connect my 'new' Pi to my 'old' wordclock. Do you know how i  can  install an old  version of your wordclock?

**Comment by Nthl25** [comment]
It is not an error in your wordclock software, sorry for my mistake.

I think it was something lika a cold soldering point on my LED stripes.
Now It is working with your latest software!

**Comment by bk1285** [comment]
Ok. Thanks for resolving!
