### ISSUE TITLE
Position of holes

### ISSUE THREAD

**Issue by Tihmann** [bk1285/rpi_wordclock#53]
I have modified the file bernds wiring to see the position of the holes. Could you check ? I could provide you with the svg file as well if you tell me your email adress. SVG upload is not possible....
[position.pdf](https://github.com/bk1285/rpi_wordclock/files/659438/position.pdf)

**Comment by bk1285** [comment]
Hi @Tihmann,

thanks for providing the file. So far I used this script https://github.com/bk1285/rpi_wordclock/blob/master/create_layout.py to create various layouts. Therefore, I'd prefer to create a new mode, which exclusively creates the position of the holes. With the script, you're ready to dynamically reproduce it for any kind of wiring (bernd, christian, etc....)

.... I'll give it a closer look.

Regards,
Bernd
