### ISSUE TITLE
Documentation of Hohlstecker / Buchse

### ISSUE THREAD

**Issue by Tihmann** [bk1285/rpi_wordclock#54]
Could you add the following information concerning the Hohlstecker to the documentation:

https://de.wikipedia.org/wiki/Hohlstecker
https://www.mikrocontroller.net/topic/144329

And the USB Cable

http://www.expli.de/uploads/images/usb-kabel-123929397184_19680.jpg

**Comment by bk1285** [comment]
Done ;)
https://github.com/bk1285/rpi_wordclock/commit/af71b430a68b5076cfbfbb5eac8039ea90309b6a
