### ISSUE TITLE
Button functions

### ISSUE THREAD

**Issue by Yoghurt02** [bk1285/rpi_wordclock#56]
Hey all,
I've now also added three buttons.
I've figured out that the left button changes the clock colors.
But what do the other buttons do?
How can I enter the other plugins like Matrix, temperature and so on?

**Comment by Yoghurt02** [comment]
I've seen that Pin 22 should change the plugin but after I've pressed it it always writes "Running plugin time_default".
In the config all the plugins are set true and in the startup it lists the plugins from 0 to 10.
Anybody an idea what is missing?

**Comment by bk1285** [comment]
Hm... Expect the wordclock to behave as outlined within this video: https://youtu.be/wcLQDykRBbM 
Anything else would be wrong and strange... :/

Can you activate the color wheel by pressing the 3rd button?

Regards,
Bernd

**Comment by Yoghurt02** [comment]
Hi Bernd, 
3rd Button is the "return" button, right?
It doesn't change the plugin. Sometimes the lights are flashing. If I press again, they stop.
If i check it in the command window, for each "return"-Button press it says "Running plugin time_default". 
For me that means button press is recognized but it's not changing the plugin.

**Comment by bk1285** [comment]
Do you have besides the default plugin other plugins enabled? If so, you should be able to change between them.

Regards.

**Comment by Yoghurt02** [comment]
Yes. In the config file I have enabled all of them...

**Comment by bk1285** [comment]
Please reopen, if necessary.

Best,
Bernd
