### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by danielschmaltz** [bk1285/rpi_wordclock#62]
I copied @euchkatzl s fork and I also installed his Android App. Whenever I look for the host in the settings by entering the IP, the App does not find the Wordclock.
Is this App working already and does anybody have an idea for solving my problem?

Best, Daniel

**Comment by bk1285** [comment]
Hi @danielschmaltz,
possibly talk to @mrksngl or check his repositories.

Alternatively, there's a webinterface to come (checkout the according branch within this repository -- while it's still highly experimental)
