### ISSUE TITLE
Alternatives Layout als deutsche Sprachvariante

### ISSUE THREAD

**Issue by SebVoss** [bk1285/rpi_wordclock#67]
Hallo Bernd,

// SORRY, hat doch noch Bugs.

**Comment by bk1285** [comment]
Hi SebVoss,

cool! Vielen Dank für den Input! Here we go:
https://github.com/bk1285/rpi_wordclock/commit/6b0a202bb4356f7912d3f82921336c36096b57cf

VG,
Bernd

2017-08-28 0:25 GMT+02:00 SebVoss <notifications@github.com>:
