### ISSUE TITLE
Adding new display: ELV ID200

### ISSUE THREAD

**Issue by c64emulator** [bk1285/rpi_wordclock#70]
Hi,
I like this project!

Is it possible to use a ID100 or ID200  (see [https://www.elv.de/elv-info-display-id200-bausatz.html](https://www.elv.de/elv-info-display-id200-bausatz.html)) from ELV as display? 

There is a docu of the interface of the ID100: [https://www.elv.de/Das-LED-Info-Display-selbst-programmieren-%E2%80%93-Demoanwendung-ID100/x.aspx/cid_726/detail_42347](https://www.elv.de/Das-LED-Info-Display-selbst-programmieren-%E2%80%93-Demoanwendung-ID100/x.aspx/cid_726/detail_42347)

**Comment by bk1285** [comment]
Hi @c64emulator,
thank you for your feedback on the project. I don't have the integration of ID100/200 on my agenda, but feel free to go for it: If you come up with a well-tested and robust solution, I'd happily integrate it to the project.
If you have any further comments on that topic, feel free to reopen this issue at any time.
Regards,
Bernd
