### ISSUE TITLE
Broken Amazon Links

### ISSUE THREAD

**Issue by ebarlas** [bk1285/rpi_wordclock#77]
I'm not able to view the Amazon links. Any suggestions?

![screen shot 2018-01-01 at 10 50 26 am](https://user-images.githubusercontent.com/221014/34470219-a789a308-eee1-11e7-8ff6-a7c0a60aed7a.png)

**Comment by bk1285** [comment]
Indeed... :/

However, to a certain extend: 3rd party issue without any chance to get the page back, I fear.... 

So you need a list of components, right?

Best,
Bernd

**Comment by ebarlas** [comment]
Yes, that's right. The list under general considerations is excellent, but specific parts would be very useful as well.

**Comment by BjornHoorelbeke** [comment]
Great project!! I would also be interested in which components to order, can you please provide a list?

**Comment by bk1285** [comment]
Here we go...:

- The LEDs: https://www.ebay.de/itm/5m-150-RGB-LED-Strip-Stripe-schwarz-mit-WS2812B-5050-SMD-WS2812-30-LEDs-m-T9-/122407573083?hash=item1c800f565b
  - Ensure, that the spacing fits your clock size (letter spacing)
- A Raspberry Pi + SD-card
  - E.g. RPi0 with Wifi is a nice choice
- A power supply: https://www.amazon.de/gp/product/B01NAN9QUD/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1
- Optionally: Some buttons: https://www.amazon.de/gp/product/B00JFTAIQS/ref=oh_aui_detailpage_o06_s00?ie=UTF8&psc=1
