### ISSUE TITLE
Q: Wiring "up-down-up", - why?

### ISSUE THREAD

**Issue by Ch4r0s** [bk1285/rpi_wordclock#80]
Hi,
first at all, thanks for your code. But why did you wire the up-down-style and not from left to right and back? So you have to calculate more than needed.

Greatings

**Comment by bk1285** [comment]
Hi @Ch4r0s,
the chosen style worked best for the given spacing of the stancil, I had. But feel free to use a horizontal style, if it fits your needs. I think "Christians wiring" uses a horizontal layout.

Best,
Bernd
