### ISSUE TITLE
Display PNG File

### ISSUE THREAD

**Issue by Bluetex07** [bk1285/rpi_wordclock#89]
I want to display a simple PNG file on the Clock.

Do I Need to add a Plugin with the code to show a specific png or can i add an empty plugin and put my file in the Icon folder?

Only want to display a png,no further function required.   

Maybe you can provide a plugin where we can put a png file?

**Comment by FrankX0** [comment]
Is this what you are looking for:
https://github.com/FrankX0/rpi_wordclock/commit/ba9715a3065a851f3d946dd1a2a94e73c1c19c00
This plugin will just display the logo.png file in the icons folder of the plugin.

**Comment by bk1285** [comment]
Nice, @FrankX0! :)
