### ISSUE TITLE
Error in time_plugin 

### ISSUE THREAD

**Issue by schweizschweiz** [bk1285/rpi_wordclock#92]
Is anybody else facing a mistake when setting up a static IP? 
As soon as I set up the static IP I can't use the right button which lets the clock starts switching coulours continuously.
As soon as I press the button the red Cross appears and the clock shows error in time_default

Has Anyone an idea what's happening?

**Comment by bk1285** [comment]
Hi @schweizschweiz 

very strange. You can comment the try/except clause in wordclock.py to get more details: L115-122. Only L117 is relevant in this case.

Start the clock afterwards via ssh and check the log to the console.

**Comment by schweizschweiz** [comment]
I didn't have time to work on the issue yet (other projects are more interesting to work on). Next weekend or so, i will have time and try to figure it out. sorry

**Comment by schweizschweiz** [comment]
So I didn't exactly get what Bernd mentioned. So what did I do? As stupid as I am I just whiped the pi and reinstalled the whole software. I have set up the static IP again and? 
Nothing. It just works like it's supposed to do. 
I'm sorry I can't give a more detailed answer but hey, it works now 🤷
