### ISSUE TITLE
False Indentation in wordclock.py - master?

### ISSUE THREAD

**Issue by PCABG** [bk1285/rpi_wordclock#96]
Hi there
I'm not completely sure if it's an error or if I just did something wrong:
I set up the clock without buttons - and set the GPIO to high according to the guidelines, tried to only load the default time plugin, yet the clock only showed the menu-clock

Stepping through it I noticed that the program skipped lines 133-135 due to the additional indentation, 
I removed the indent to a level to the left and now it works...

any feedback on that?
thanks

**Comment by bk1285** [comment]
Hi @PCABG thanks for reporting. Can you check latest master for correct functionality?

Best,
Bernd

https://github.com/bk1285/rpi_wordclock/commit/93e33c75bf05471f779dadebef83ccb3f0273a93
