### ISSUE TITLE
Red and green colours swapped

### ISSUE THREAD

**Issue by FrankX0** [bk1285/rpi_wordclock#99]
With the current master (and develop) branche the red and green colours are swapped.
I am still running a branch from April this year which works fine.
With the new branches e.g. the matrix is red instead of green.

**Comment by bk1285** [comment]
Hey FrankX0, indeed! Thanks for reporting. I pushed a fix.

Please reopen, if the colors are still wrongly mapped.

Best,
Bernd

**Comment by FrankX0** [comment]
Fixed!

Thanks Bernd.
